services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - library-system_pgdata:/var/lib/postgresql/data


  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/library
    depends_on:
      - db
    ports:
      - "8000:8000"


volumes:
  library-system_pgdata:
